[database]
    Dialect = "mysql"
    Database = ""
    User = ""
    Password = ""
    Charset = "utf8mb4"         #要支持emoji的话，填 utf8mb4 
    Host = ""      #数据库ip
    Port = 3306                 #数据库端口 dev: 63621 prod: 
    MaxIdleConns = 5            #空闲时最大的连接数
    MaxOpenConns = 10           #最大的连接数

[redis]
    Host = "127.0.0.1"      #redis所在机器的ip
    Port = 6379                 #redis的端口
    Password = ""       #redis的密码，若无密码，可不填
    MaxIdle = 3                 #最大的空闲连接数
    MaxActive = 5               #最大的激活连接数

[mongodb]
    URL = ""                    #mongodb连接地址, 可以不填，不填的话,就没有计划任务和数据统计功能
    Database = "golang123"

[statsd]
    URL = ""                    #statsd服务连接地址，如127.0.0.1:8125
    Prefix = ""                 #statsd客户端前缀，可留空
[chrome]
    Headless = false             #谷歌浏览器无头参数
    Env = "production"
[rabbitmq]
    Host = ""
    User = ""
    Password = ""

[server]
    APIPoweredBy = ""           #后台go加的X-Powered-By
    SiteName = ""               #网站名称
    Host = ""                   #网站域名
    ImgHost = "" #图片服务器域名
    Env = "production"         #模式(开发，测试，产品)
    LogDir = "./log"                 #日志文件所在的目录，如果不设的话，默认在项目目录下
    APIPrefix = "/api"          #api服务请求前缀
    UploadImgDir = "/root/upload/images"
    ImgPath = ""              #上传后的图片请求地址前缀
    WxAppImgPath = "/root/upload/images/" #wxapp的图标存放路径
    MaxMultipartMemory = 20     #上传的图片最大允许的大小，单位MB
    Port = 8004                 #go监听的端口
    CronEnabled = true          #是否允许计划任务
    TokenSecret = "" #TokenSecret，请修改
    TokenMaxAge = 86400         #token多久过期，单位秒, 86400是24小时
    PassSalt = ""       #用户密码加盐，请修改
    CrawlerName = "超级苦工"     #爬虫账号名
    LuosimaoVerifyURL = ""      #螺丝帽验证地址
    LuosimaoAPIKey = ""         #螺丝帽api_key
    MailUser = ""               #域名邮箱账号
    MailPass = ""               #域名邮箱密码
    MailHost = "smtp.qq.com"    #smtp邮箱域名
    MailPort = 465              #smtp邮箱端口
    MailFrom = ""               #邮件来源
    Github = "https://github.com/cnfox"
    BaiduPushLink = ""
    SessionID = ""