[database]
Dialect = "mysql"
Database = "rod"
User = "root"
Password = "admin980921"
Charset = "utf8mb4"         #要支持emoji的话，填 utf8mb4
Host = "127.0.0.1"      #数据库ip
Port = 3306                 #数据库端口 dev: 63621 prod:
MaxIdleConns = 5            #空闲时最大的连接数
MaxOpenConns = 10           #最大的连接数

[redis]
Host = "127.0.0.1"      #redis所在机器的ip
Port = 6379                 #redis的端口
Password = ""       #redis的密码，若无密码，可不填
MaxIdle = 3                 #最大的空闲连接数
MaxActive = 5               #最大的激活连接数

[chrome]
Headless = false             #谷歌浏览器无头参数
Env = "dev"
[server]
Env = "production"         #模式(开发，测试，产品)
MaxMultipartMemory = 20     #上传的图片最大允许的大小，单位MB
Port = 8004                 #go监听的端口